#!/bin/sh

#SBATCH -A DBS21007
#SBATCH --job-name=ds002336-mriqc
#SBATCH --mail-type=END
#SBATCH --mail-user=jbwexler@tutanota.com
#SBATCH --output=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds002336-mriqc/.reproman/jobs/local/20220304-033839-42c5/stdout
#SBATCH --error=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds002336-mriqc/.reproman/jobs/local/20220304-033839-42c5/stderr

#SBATCH --nodes=2
#SBATCH --ntasks=10
#SBATCH --time=8:00:00
#SBATCH --partition=small

metadir=/scratch1/03201/jbwexler/openneuro_derivatives/derivatives/mriqc/ds002336-mriqc/.reproman/jobs/local/20220304-033839-42c5

module load launcher
module load remora
export LAUNCHER_JOB_FILE="$metadir/launcher"

for task_id in $(seq 0 9); do
    printf "$metadir/runscript %d >$metadir/stdout.%d 2>$metadir/stderr.%d\n" \
      "$task_id" "$task_id" "$task_id" >>"$LAUNCHER_JOB_FILE"
done

remora "$LAUNCHER_DIR"/paramrun